spring:
  application:
    name: business-oauth2
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 123.207.111.152:8848
dubbo:
  scan:
    base-packages: person.pulei.myshopplus.business.controller, person.pulei.myshopplus.business.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://123.207.111.152:8848
server:
  port: 9001
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 开启 Feign 的 OKHttp 方式
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false

business:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret